sudo: required
services:
  - docker
env:
  global:
    - SHA=$(git rev-parse HEAD)
    - DOCKER_ID="$DOCKER_ID"
    - DOCKER_PASSWORD="$DOCKER_PASSWORD"
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1
before_install:
  - openssl aes-256-cbc -K $encrypted_9f3b5599b056_key -iv $encrypted_9f3b5599b056_iv -in service-account.json.enc -out service-account.json -d
  - curl https://sdk.cloud.google.com | bash > /dev/null;
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud components update kubectl
  - gcloud auth activate-service-account --key-file service-account.json
  - gcloud config set project taskaholic-284504
  - gcloud config set compute/zone us-central1-a
  - gcloud container clusters get-credentials taskaholic-cluster
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker build -t curtiscodes/react-test -f ./frontend/Dockerfile.dev ./frontend

script:
  - docker run -e CI=true curtiscodes/react-test npm run test

deploy:
  provider: script
  script: bash ./deploy.sh
  on:
    branch: main
