apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      component: backend
  template:
    metadata:
      labels:
        component: backend
    spec:
      containers:
        - name: backend
          image: curtiscodes/taskaholic-backend
          ports:
            - containerPort: 5000
          env:
            # production || development
            - name: NODE_ENV
              value: production
            - name: PORT
              value: '5000'
            # MongoDB
            - name: MONGO_INITDB_DATABASE
              valueFrom:
                secretKeyRef:
                  name: mongodatabase
                  key: MONGO_INITDB_DATABASE
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongouser
                  key: MONGO_INITDB_ROOT_USERNAME
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongopassword
                  key: MONGO_INITDB_ROOT_PASSWORD
            # JWT
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: jwtsecret
                  key: JWT_SECRET
            - name: JWT_EXPIRE
              value: 30d
            - name: JWT_COOKIE_EXPIRE
              value: '30'
            # Email service
            - name: FROM_EMAIL
              value: support@taskaholic.com
            - name: FROM_NAME
              value: Daniel at Taskaholic
      imagePullSecrets:
        - name: regsecret
